import{a as L,S as w,i as d}from"./assets/vendor-CjwUT-lV.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&n(g)}).observe(document,{childList:!0,subtree:!0});function e(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=e(o);fetch(o.href,r)}})();const A="48961514-d720aad073d42be14fd4daf93",C="https://pixabay.com/api/";async function f(t,s=1){try{const e=await L.get(C,{params:{key:A,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:15}});return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Error fetching images:",e),iziToast.error({message:"An error occurred while fetching images. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),{images:[],totalHits:0}}}const h=document.querySelector(".gallery"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function b(){h.innerHTML=""}function F(t){b();const s=t.map(e=>`
        <li class="img-card">
            <a href="${e.largeImageURL}">
                <img 
                    src="${e.webformatURL}" 
                    alt="${e.tags}" 
                    data-source="${e.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",s),S.refresh()}const y=document.querySelector("form"),l=document.querySelector(".loader-first"),c=document.querySelector(".loader-bottom"),i=document.querySelector(".btn-loadmore");document.querySelector(".gallery");let a=1,m="",u="",p=0;y.addEventListener("submit",async t=>{t.preventDefault();const e=t.target.querySelector("input").value.trim();if(!e){d.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}e!==m&&(a=1,m=e,u=e,b(),i.style.display="none"),l&&(l.style.display="block");try{const{images:n,totalHits:o}=await f(u,a);if(p=o,!(n!=null&&n.length)){d.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),i.style.display="none";return}F(n,a),a++,i.style.display=a*15<p?"block":"none"}catch(n){console.error(n),d.error({message:"Failed to fetch images. Please check your internet connection.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{l&&(l.style.display="none")}y.reset()});i.addEventListener("click",async()=>{i.style.display="none",c&&(c.style.display="block");try{const{images:t}=await f(u,a);if(!(t!=null&&t.length)){i.style.display="none";return}F(t,a),a++,i.style.display=a*15<p?"block":"none",q()}catch(t){console.error(t),d.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{c&&(c.style.display="none")}});function q(){const t=document.querySelector(".img-card");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
