import{a as b,S as F,i as n}from"./assets/vendor-D3PmPE7A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const A="48961514-d720aad073d42be14fd4daf93",L="https://pixabay.com/api/";async function y(t,r=1){try{const s=await b.get(L,{params:{key:A,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}});return{images:s.data.hits,totalHits:s.data.totalHits}}catch(s){return console.error("Error fetching images:",s),iziToast.error({message:"An error occurred while fetching images. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),{images:[],totalHits:0}}}const C=document.querySelector(".gallery");function f(t){const r=t.map(o=>`
        <li class="img-card">
            <a href="${o.largeImageURL}">
                <img 
                    src="${o.webformatURL}" 
                    alt="${o.tags}" 
                    data-source="${o.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${o.likes}</p>
                <p><strong>Views:</strong> ${o.views}</p>
                <p><strong>Comments:</strong> ${o.comments}</p>
                <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
        </li>`).join("");C.insertAdjacentHTML("beforeend",r),new F(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const p=document.querySelector("form"),c=document.querySelector(".loader-first"),g=document.querySelector(".loader-bottom"),l=document.querySelector(".btn-loadmore"),h=document.querySelector(".gallery");let i=1,m="",u="";function w(){h.innerHTML=""}p.addEventListener("submit",async t=>{t.preventDefault();const s=t.target.querySelector("input").value.trim();if(s===""){n.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}u=s,s!==m&&(i=1,m=s,h.innerHTML="",l.style.display="block"),c&&(c.style.display="block");try{const{images:o,totalHits:e}=await y(u,i);if(!o||o.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}w(),f(o,i),i*15>=e?(n.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),l.style.display="none"):l.style.display="block",i++}catch{n.error({message:"Error",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{c&&(c.style.display="none")}p.reset()});l.addEventListener("click",async()=>{g&&(g.style.display="block",console.log("Loading bottom message shown"));try{const{images:t,totalHits:r}=await y(u,i);t&&t.length>0&&(f(t,i),i++,i*15>=r?(n.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),l.style.display="none"):l.style.display="block",E())}catch{n.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{g&&(g.style.display="none")}});function E(){const t=document.querySelector(".img-card");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
