import{a as h,S as F,i as l}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&i(g)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const b="48961514-d720aad073d42be14fd4daf93",A="https://pixabay.com/api/";async function f(o,r=1){try{const t=await h.get(A,{params:{key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:40}});return{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){return console.error("Error fetching images:",t),iziToast.error({message:"An error occurred while fetching images. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"}),{images:[],totalHits:0}}}const u=document.querySelector(".gallery");function y(o,r){r===1&&(u.innerHTML="");const t=o.map(e=>`
        <li class="img-card">
            <a href="${e.largeImageURL}">
                <img 
                    src="${e.webformatURL}" 
                    alt="${e.tags}" 
                    data-source="${e.largeImageURL}" 
                />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${e.likes}</p>
                <p><strong>Views:</strong> ${e.views}</p>
                <p><strong>Comments:</strong> ${e.comments}</p>
                <p><strong>Downloads:</strong> ${e.downloads}</p>
            </div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",t),new F(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const p=document.querySelector("form"),n=document.getElementById("#loading-message"),c=document.querySelector(".btn-loadmore");let a=1,m="",d="";p.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.querySelector("input").value.trim();if(t===""){l.error({message:"Please fill in the field!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}d=t,t!==m&&(a=1,m=t),c.style.display="none",n&&(n.style.display="block"),console.log("Loading message shown");try{const{images:i,totalHits:e}=await f(d,a);if(!i||i.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"});return}y(i,a),a*40>=e?(c.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})):c.style.display="block",a++}catch{l.error({message:"Error",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{n&&(n.style.display="none")}p.reset()});c.addEventListener("click",async()=>{n&&(n.style.display="block"),console.log("Loading message shown");try{const{images:o,totalHits:r}=await f(d,a);o&&o.length>0&&(y(o,a),a++,a*40>=r&&(c.style.display="none",l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})),L())}catch{l.error({message:"Error loading more images",position:"topRight",messageColor:"#FAFAFB",backgroundColor:"#EF4040"})}finally{n&&(n.style.display="none")}});function L(){const o=document.querySelector(".img-card");if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
